name: LukesWhimsy
version: '1.2'
main: me.nohbdyexe.lukesWhimsy.LukesWhimsy
author: nohbdy-exe
website: https://github.com/nohbdy-exe/lukeswhimsy
api-version: '1.21'
commands:
  smite:
    description: Smite a player with lightning.
    usage: /<command> <player>
  sit:
    description: Sit somewhere, or on someone else's head, or make another player sit on another player's head.
    usage: /<command> [player] [player]
  fling:
    description: Fling yourself or a player with varying levels of knockback.
    usage: /<command> [player] [knockback]
  onepunchman:
    description: Become the hero you were born to be.
    usage: /<command>
  catapult:
    description: Launch a giant projectile into the skies.
    usage: /<command>
  heal:
    description: Heal yourself.
    usage: /<command>
  feed:
    description: Feed yourself.
    usage: /<command>
  fly:
    description: Enable flying mode for yourself.
    usage: /<command>
  whimsyhelp:
    description: A list of all my whimsical commands.
    usage: /<command>
  hng:
    description: Make a villager noise.
    usage: /<command>
  babytrap:
    description: Toggle on/off to trap other players that hit you, or summon 10 baby zombies at target location.
    usage: /<command> [player]
  rtp:
    description: Teleports you to a random location.
    usage: /<command>
  back:
    description: Returns you to your last saved location (via rtp).
    usage: /<command>
